### ISSUE TITLE
 Payments Due list days overdue(No color change)

### ISSUE THREAD

**Issue by diiman2000** [OCA/account-payment#115]
On the payment due list view the colour of the over due payment does not change to red even if the invoice is 13 days overdue. Please can you help me?

![screenshot 2016-11-19 01 05 04](https://cloud.githubusercontent.com/assets/5080681/20451725/c489262e-adf4-11e6-8c4a-ddd26a4a3425.png)

**Comment by pedrobaeza** [comment]
Please reproduce this on runbot, because you have a custom theme that can affect. Meanwhile, I close.
