### ISSUE TITLE
account_due_list install takes too much time

### ISSUE THREAD

**Issue by caguimore** [OCA/account-payment#125]
If you install the account_due_list to a database with a lot of account_move_lines (i.e. < 100.000) the calculation of store values takes too much time.

**Comment by pedrobaeza** [comment]
Yeah, but it's the needed time. No possible solution.

**Comment by JordiBForgeFlow** [comment]
On v8 there is an init hook that speeds up the install 

https://github.com/OCA/account-payment/blob/8.0/account_due_list/init_hook.py

Are you using the latest code?

**Comment by pedrobaeza** [comment]
I'm assuming it is using it. Anyway, it takes time, so please don't open again the issue. It's crystal clear.
