### ISSUE TITLE
account_payment_batch_process

### ISSUE THREAD

**Issue by max3903** [OCA/account-payment#134]
At @ursais, we have a module to select multiple invoices from the vendor bill list view or from our aging  module (equivalent to account_due_list) and generate all the payments (grouped by vendor).

I think this repository would be the best fit to host it, unless the feature already exists in a module I haven't found.

Any opinion? Interest?

Thanks.

**Comment by pedrobaeza** [comment]
But this is what account_payment_order does with the option of transferring the balance to the selected bank account, so you don't need this module at all.

**Comment by max3903** [comment]
@pedrobaeza Thanks!

**Comment by max3903** [comment]
Hello @pedrobaeza 

I have been evaluating account_payment_order:
- We don't need a document like the payment order to track the list of invoices part of the same payment order
- We don't need SEPA stuff

account_payment_batch_process provides a simple way to select multiple invoices (from the invoice list view or our partner aging module) to create payments.

Accountants look at their supplier aging, select the invoices they want to pay and create the payments in batch, that's it. No need to keep track of the invoices selected.

No relation with the bank either, so I think this repo is a good fit and our module is relevant.

**Comment by pedrobaeza** [comment]
Well, SEPA has nothing to do with account_payment_order (they are different modules), but SEPA orders can also be made with this. There's a very simple way in this module to select multiple invoices: just select them in the list view, and click on Action > Add to payment order.

**Comment by max3903** [comment]
@pedrobaeza We don't want a payment order, just a list of payments.

**Comment by pedrobaeza** [comment]
It's the same, but with another name.

**Comment by max3903** [comment]
@pedrobaeza 

Look at https://github.com/OCA/account-payment/pull/138/files, there is no object to store the list of payments...

**Comment by pedrobaeza** [comment]
OK, as you want. I don't see the goal for this module having the other, but if people see it, then go ahead.

**Comment by max3903** [comment]
@pedrobaeza Thanks!
