### ISSUE TITLE
Cash Flow Forecast

### ISSUE THREAD

**Issue by angelmoya** [OCA/account-payment#144]
I'm planning to test and migrate account_treasury_forecast modules  from https://github.com/odoomrp/odoomrp-wip to this repo on version 10, any comment about it @pedrobaeza

**Comment by pedrobaeza** [comment]
Well, I was not involved on this module and I also don't see how to work with it in a practical way (I only see manual entries, but without proper automatisms).

@anajuaristi can tell you more about this.

**Comment by angelmoya** [comment]
OK, I'm testing and it's working ... but as you said it's only manual way.

Maybe it could be better to develop new module, like account_due_list, that show on sql view info about due list and forecast. And forecast could be new object account.payment.forecast with other field called type that can be:
- payment (from accounting)
- draft invoices
- sales and purchases
- manual forecast

On new view for forecast we can show account_due_list elements as type "payment" and other account.payment.forecast elements

## Draft invoices
On create and write invoices, create new account.payment.forecast by date due.
On invoice validate or invoice unlink, unlink this account.payment.forecast.

## Sales and Purchases
On create and write sale or purchase order, create new account.payment.forecast by date due.
On invoice validate or invoice unlink, unlink this account.payment.forecast.

## Manual forecast
Create account.payment.forecast manually

This way you can get this forecast dimacally and use reporting view to filter.

What do you think @pedrobaeza @anajuaristi

**Comment by angelmoya** [comment]
If someone want to check account_treasury_forecast on version 10, code is working on this branch:

 https://github.com/PESOL/account-payment/tree/ADD-10-account_treasury_forecast

But for the moment I will not do the PR

**Comment by D4N** [comment]
@angelmoya I like your draft, such a module would be great to have. I would also like to add reoccurring monthly expenses (like rent, employee wages, average expenses for gas, insurances, etc.) to the forecast. However, the monthly expenses should be maybe put in a separate module, as they might be also useful for reconciliation.

Do you intend to work on your draft? If yes, I would offer my help.

**Comment by pedrobaeza** [comment]
Any news on this, @angelmoya, or should we close it?

**Comment by angelmoya** [comment]
I'm not working on it.... maybe this functionality could be done better with missbuilder

**Comment by pedrobaeza** [comment]
OK, closing then.
