### ISSUE TITLE
Check number wrapping

### ISSUE THREAD

**Issue by marcbritten** [OCA/account-payment#160]
Hi using account_check_printing_report_dlt103 the middle and bottom section Check # field the check number wraps and is printed under the words Check # - this causes the number to overlap the word Payment.  I'm also getting a 2nd page - possibly because check amount on the 3rd portion is right up against the margin.

[Payment Check DLT103.pdf](https://github.com/OCA/account-payment/files/1326022/Payment.Check.DLT103.pdf)

**Comment by LoisRForgeFlow** [comment]
Do you have installed the module [report_wkhtmltopdf_param](https://github.com/OCA/reporting-engine/tree/10.0/report_wkhtmltopdf_param)?

**Comment by marcbritten** [comment]
Yes.

Odoo 10.0.20170816, with wkhtmltopdf 0.12.2.4-1 on Ubuntu 16.04

account_check_printing_report_base and dlt103 and  report_wkhtmltopdf_param downloaded from GIT repo and installed manually via the interface,.

**Comment by pedrobaeza** [comment]
@lreficent do you have any clue then?

**Comment by JordiBForgeFlow** [comment]
@marcbritten You should use wkhtmltopdf 0.12.4 (with patched qt)
