### ISSUE TITLE
[10.0] account_payment_return: leaving open value under AR

### ISSUE THREAD

**Issue by hartscott** [OCA/account-payment#173]
This module is awesome! Thank you. 

I am however having trouble with the module under v10. Once you have registered the NSF it continues to show an balance under AR even after you have registered the replacement payment. When I run the test, on your runbot and it's actually showing the exact same journal entries per transaction.

When we run a Due Payment Report or Partner Ledger it shows a $0 balance, but when we run the Open Items Report from OAC Accounting Reports it's showing a balance. Maybe there report is inaccurate in pulling data, but it's still tracking a positive back into AR which would skew the numbers no?

Again, THANK YOU for this module. It's honestly an oversite imo for people that still accept check payments or deal with charge backs.

**Comment by pedrobaeza** [comment]
Which module?

**Comment by hartscott** [comment]
account_payment_return

I can provide you with screen shots. It's an amazing module since Odoo
overlooked this crucial part.

**Comment by pedrobaeza** [comment]
Please describe the exact steps followed for getting the problem and try the same on runbot (click on "Try me on runbot" button on the README).

**Comment by hartscott** [comment]
I keep trying to use the Runbot but it looks like the build was destroyed.
Tried creating a new db but it won't allow. Attached is a video of what we
are seeing. If you see something that is wrong please let me know, but I
believe everything is correct. Once you run the Open report it credits the
repayment back into the system as an open item.

**Comment by pedrobaeza** [comment]
The video is not attached here in GitHub. You should try directly from GitHub interface or upload it in any other place.

**Comment by hartscott** [comment]
Sorry about that!

https://drive.google.com/open?id=1AAjLt3HV36jsOAEgs4ck8V_2MZMlhVVv

**Comment by pedrobaeza** [comment]
As this is a public issue, you should give public permission to the video.

**Comment by hartscott** [comment]
Sorry was using gDrive but didn't realize you couldn't openly share. Never really needed to before...

[nsf-2018-03-21_07.50.45.mkv.zip](https://github.com/OCA/account-payment/files/1839631/nsf-2018-03-21_07.50.45.mkv.zip)

**Comment by pedrobaeza** [comment]
I have seen the video, but you are still not showing the problem. You are saying that the report is not correct, but I don't see that report nor what is the kind of problem. Sorry, but this overpasses the kind of free assistance I can give, and I think it's a misunderstanding of the use of the module, so I close the issue and you should contact any partner that can advise you.
