### ISSUE TITLE
Account payment return: Why only reconcilied move lines?

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/account-payment#183]
Is there a reason for not being able to make a refund, for example, an advance payment?
https://github.com/OCA/account-payment/blob/7222b3fd30c520f3a660f89d5b103cd292b1ee7f/account_payment_return/views/payment_return_view.xml#L38-L44

**Comment by pedrobaeza** [comment]
Refunds are not receivable, but payable, so I don't get it...

**Comment by DarioLodeiros** [comment]
I mean if the company has a customer payment without reconcilied (in advance)

**Comment by pedrobaeza** [comment]
Well, that's not something covered right now, as for returning something, you need to have a reconcile with the payment order or similar.

**Comment by DarioLodeiros** [comment]
Ok, I tested it with this module and if I do a customer payment (not reconcilied) refund, the payment and the refund are reconcilied between them. Its only necessary drop the reconlied domain in xml move field... I can make a little PR if you see it well.
Thanks!

**Comment by pedrobaeza** [comment]
I don't have it clear, as there's a unreconcile operation in between, and I still don't see the flow. @carlosdauden what do you think?

**Comment by pedrobaeza** [comment]
@carlosdauden can you please give feedback?
