### ISSUE TITLE
[11.0] account_due_list_payment_mode & account_payment_partner issue

### ISSUE THREAD

**Issue by angelmoya** [OCA/account-payment#208]
Hi,

module account_due_list_payment_mode create payment_mode_id field on account.move.line as related='invoice_id.payment_mode_id', so it's not editable.

Module account_payment_partner create other field with same name, but not as related, this field is editable and is set on invoice validation.

For user is usefull to get this field editable on account_due_list.

Module account_due_list_payment_mode depends account_payment_partner, I think that could be better to don't redefine this field and allow to edit on account due list.

**Comment by pedrobaeza** [comment]
This is a bad migration coming from previous where `account_payment_partner` doesn't include this module. Clearly `account_due_list_payment_mode` should display existing field, not to create a new one.

**Comment by angelmoya** [comment]
Ok, I fix it on  #210
