### ISSUE TITLE
[12.0] [RFC] Account Payment Return Import SEPA PAIN: reason codes

### ISSUE THREAD

**Issue by ThomasBinsfeld** [OCA/account-payment#226]
The [ISO20022 documentation](https://www.iso20022.org/external_code_list.page) lists 225 return codes while the [OCA addon](https://github.com/OCA/account-payment/blob/12.0/account_payment_return_import_sepa_pain/data/unpaid_reason_codes.xml) lists 20 codes. Shouldn't all these missing codes be added in the OCA addon?

**Comment by pedrobaeza** [comment]
Well, I don't remember well the source of this, but 225 can be too much, isn't it? Should we put all of them or only the most use ones?

**Comment by sbidoul** [comment]
Question is: how to know which are the most used ones? I propose to add them all. 

If at some point people combine manual entry of return with PAIN import, one possibility could be adding active flag on return codes so they don't appear in the drop down list, while the import code could still use them.

**Comment by ThomasBinsfeld** [comment]
Would a XML file the best way to embed the 225 return reasons in the module (in terms of maintainability) ? I don't know if it can be done with a CSV file (no `noupdate` option).

**Comment by pedrobaeza** [comment]
As this is standard, it can be tolerable to be put as CSV noupdate=0, as you shouldn't touch here. If you want, then create others. What do you think?

**Comment by ThomasBinsfeld** [comment]
Done in 12.0, I close this issue.
