### ISSUE TITLE
[12.0] [RFC] Account Payment Return Import SEPA PAIN: NARR reason

### ISSUE THREAD

**Issue by ThomasBinsfeld** [OCA/account-payment#227]
In a SEPA payment status report, the reason code can be [NARR](https://www.iso20022.org/external_code_list.page), meaning the description doesn't match any reason code but is described in the `AddtlInf` tag. 

Shouldn't the OCA addon manage these narrative reasons?

**Comment by pedrobaeza** [comment]
Yes, but it supposes to add a new field for free text. Maybe on the main module?

**Comment by sbidoul** [comment]
+1 for a free text field on return lines in the main module.

**Comment by ThomasBinsfeld** [comment]
Done in 12.0, I close this issue.
