### ISSUE TITLE
[12.0] [RFC] Account Payment Return: import CAMT

### ISSUE THREAD

**Issue by ThomasBinsfeld** [OCA/account-payment#235]
Is there something existing to import SEPA Direct Debit returns from `camt.054.001.02` files? For now we only have [account_payment_return_import_sepa_pain](https://github.com/OCA/account-payment/tree/12.0/account_payment_return_import_sepa_pain) that manages the technical rejections from `pain.002.001.03` files. All return codes are already in it.

------------------
[iso20022](https://www.iso20022.org/message_archive.page)

**Comment by pedrobaeza** [comment]
I don't know any. I suppose this would be a module `account_payment_return_import_camt`.

**Comment by ThomasBinsfeld** [comment]
Thanks @pedrobaeza. I'm on it.

**Comment by ThomasBinsfeld** [comment]
The [codes set](https://github.com/OCA/account-payment/blob/12.0/account_payment_return_import_sepa_pain/data/payment.return.reason.csv) and probably [this override](https://github.com/OCA/account-payment/blob/12.0/account_payment_return_import_sepa_pain/models/payment_return.py) will be common to both import modules (`account_payment_return_import_sepa_pain` and `account_payment_return_import_sepa_camt`). Should I externalize the codes and the override in a base module (`account_payment_return_import_sepa_base`)?

We could also merge the two SEPA import modules in one but it would mean a renaming of the PAIN import module (maybe in the next Odoo version?).

**Comment by pedrobaeza** [comment]
I vote for merging both, and as v12 is recently migrated, the renaming is still allowed. @sbidoul what do you think?

**Comment by sbidoul** [comment]
I'm fine with merging both. If a renaming has to be done, it could be account_payment_return_import_iso20022.
