### ISSUE TITLE
[account_payment_return] Cannot reconcile with bank statement

### ISSUE THREAD

**Issue by jalzaga** [OCA/account-payment#283]
When we create a payment return related to an invoice paid through a debit order, it creates the corresponding journal entry and it lets the invoice unpaid. The problem is that you cannot reconcile de unpaid amount with the bank statement because it is not shown in blue as the original payment.
To recreate the situation just create an invoice with a direct debit payment mode an include it in a debit order. The payment mode is set with offsetting_account = bank account
You can confirm the debit order so that the invoice becomes paid and you can reconcile the payment with the bank statement because it is shown in blue at the reconciliation screen.
Then you create a payment return for that invoice and confirm it, so that a journal entry is created. The account move contains the credit to the bank account but it does not appear in the reconciliation screen. I guess because there is no bank payment line create for that return.
I tested in runbot version 11.

**Comment by jalzaga** [comment]
There is no answer to this issue since September, 9. There are customers waiting for a solution to it. We know there is a workaround using a transfer account but it is not the best.
Please give feedback about it.

**Comment by rafaelbn** [comment]
Hi @jalzaga ,

In which version?

I don't have any issue.

Maybe you can make a PR to solve it?

**Comment by jalzaga** [comment]
I tested in v11 but I guess its also in v10 and v12 @rafaelbn

**Comment by jalzaga** [comment]
@rafaelbn is there any news about this issue?

**Comment by enricostano** [comment]
@jalzaga do you think that this issue is related to #220 ?
