### ISSUE TITLE
Travis is failing for 12.0

### ISSUE THREAD

**Issue by sbejaoui** [OCA/account-payment#322]
Hi all,

Travis is failing for 12.0.

Please see https://travis-ci.org/github/OCA/account-payment.

**Comment by sbidoul** [comment]
Failing tests are in 
- account_payment_show_invoice cc /@LoisRForgeFlow
- account_payment_multi_deduction cc/ @kittiu 

It was green on Feb 22, so it's probably due to a change in Odoo.

**Comment by sbejaoui** [comment]
I pushed a fix for the two tests.

**Comment by kittiu** [comment]
Noted with thanks @sbejaoui
