### ISSUE TITLE
[10.0] [account_payment_widget_amount] Amount Paid getting assigned multiple times (Twice and Thrice also at times)

### ISSUE THREAD

**Issue by bharatrdevnani** [OCA/account-payment#363]
Dear Community Members,

I am using account_payment_widget_amount module in V10, 

When I am assigning partial amount on already partially paid or on fully unpaid invoice, the amount which I select in widget adjusts double the entered amount and also found instance where it is adjusting thrice 

And also I have traced the issue some what it is calling following function multiple times, which results into wrong calculations in assigning amount to an invoice

def update_amount_reconcile

Any pointers to this will be much appreciated!

**Comment by farazbdm** [comment]
@pedrobaeza 
this is the one i meant to PR on.
this case can be recreated on runbot as well,
when there are multiple lines of Accounts Receivable the iterations of paid_amt considers full amount for each line to match.
that causes the issue. #364

**Comment by pedrobaeza** [comment]
Great, @bharatrdevnani can you please check the PR?
