### ISSUE TITLE
[ITA] account_due_list

### ISSUE THREAD

**Issue by scigghia** [OCA/account-payment#37]
I think that it.po in account_due_list must be reviewed
https://github.com/OCA/account-payment/blob/8.0/account_due_list/i18n/it.po#L99 Pagamenti should be "Scadenze" or "lista scadenze"
it could be confused with "Pagamenti cliente" and "Pagamenti fornitore"

what do you think about?

**Comment by eLBati** [comment]
I agree. Original string `payments` should be changed too

**Comment by pedrobaeza** [comment]
This should be changed in Transifex.
