### ISSUE TITLE
[12] account_payment_return - create invoice to charge dunning expenses to customer

### ISSUE THREAD

**Issue by enricostano** [OCA/account-payment#373]
Hi,
is there a way to generate an invoice to the customer for the dunning expenses while confirming a return?
Thanks!

**Comment by pedrobaeza** [comment]
Not right now

**Comment by enricostano** [comment]
Hi @pedrobaeza !
Do you think https://github.com/OCA/account-payment/pull/316 could lead in that direction?
Also, do you think it's something we could add to this repo as a contribution?

**Comment by pedrobaeza** [comment]
It doesn't seem to be that, but new "data". A contribution adding this feature would be welcome.
