### ISSUE TITLE
account_payment_term_multi_day

### ISSUE THREAD

**Issue by Bilbonet** [OCA/account-payment#39]
hi, 
i've created a payment mode to 30 days, the days (10,25).
I've created an invoice with date 11/07/2015

The payment mode calculated the date 10/09/2015

I think that the correct day should be 25/08/2015

**Comment by pedrobaeza** [comment]
I have tried on runbot (admin/admin) and it's working as expected, so it's a problem in your side:

http://3111463-8-0-3b28c5.runbot1.odoo-community.org/web?db=3111463-8-0-3b28c5-all#id=8&view_type=form&model=account.invoice&menu_id=225&action=258
