### ISSUE TITLE
Can't use Runbot

### ISSUE THREAD

**Issue by gdgellatly** [OCA/account-payment#43]
Hi,

I just went to test a pretty sever bug I found with no_auto_lines, but using runbot you can't even open either payment screen, you just get fields missing errors (main 7.0 branch)

shadow_move_id in account_vat_on_payment is problem for customer payments
supplier_invoice_number in account_voucher_supplier_invoice_number is problem for supplier payments.

**Comment by pedrobaeza** [comment]
Closing due to aging
