### ISSUE TITLE
[paid support requested for setting up payment returns on odoo 14 CE]

### ISSUE THREAD

**Issue by TastenExpress** [OCA/account-payment#471]
Hello there,

I'm Riccardo, the founder of a little german company which rents E-Pianos and Keyboards. I have introduced odoo 14 CE a few weeks ago and we are managing all of our payments with accounting module.

I'm contacting you because for my business it is important to manage payment returns and I see that odoo is out of the box not able to handle them well (not able to reconcile it properly). So I found only few solutions about how to manage payment returns.

Currently I installed the modules on my server but I'm still wondering how to use this module in daily business. We are importing our bank statements via an EBICS connector directly from our bank. So I'm wondering which configuration is needed to let (in best case) odoo create payment returns automatically if there is such case in bank statements.

Is anyone here available to give paid support about this issue?

I'm very happy to hear from you.

Big big thanks in advance!!!

Regards, Riccardo

**Comment by JordiBForgeFlow** [comment]
@TastenExpress I do not understand your use case. Is it related to a return of a purchase order, or with a bank transfer request that was cancelled?

**Comment by TastenExpress** [comment]
Hello Jordi, thanks for your quick reply.
In talking about bank transfers that were canceled by our bank (because the customers account were we want to debit or from is insufficient f.ex.).

This occurs when using the European sepa payment method, which allows you to debit directly from your customers bank account. After sending the payment order to the bank, this payment can be rejected a few days later. 

So it is not about returns of shipped goods!

I think that the payment returns module in this repo is about my issue, am I right?

**Comment by JordiBForgeFlow** [comment]
Perhaps this is what you are looking for
https://github.com/OCA/account-payment/tree/14.0/account_payment_return_import_iso20022

**Comment by TastenExpress** [comment]
Yes, I already installed this module and I see a wizard where I can upload some file.
I fear my bank is offering camt 53 format only. At least this is the format we are downloading our bank statements. And I fear, the files I can upload via importer, is not the bank statement files, right?
What kind of files should I upload there?

Is it possible to extend this module with this kind of data format camt 53?

Any other idea?
We are currently processing bank statements in camt53 format for reconciliation. Works fine for regular payments. For return payments odoo has no idea how to reconcile it... and unfortunately we, too :-/
So any option to create a return would helpful I think. Or at least an option to mark an invoice as "payment returned". I know there is a checkbox in invoices, but seems to be read-only for dispalying return status, right?

**Comment by JordiBForgeFlow** [comment]
You can import your banl statement camt 053 files using https://github.com/OCA/bank-statement-import/tree/14.0/account_statement_import_camt

As I understand it some of the statement lines will actually be returns of previous payments. In order to handle those I assume that you need first to create am account payment return using https://github.com/OCA/account-payment/tree/14.0/account_payment_return and once you have done that, you can reconcile the payment return with the bank statement line

**Comment by TastenExpress** [comment]
Bank statements we are already importing via camt. So that's fine. And yes, some of the lines there are returns. 

Seems to be a good idea that the payment returns will be reconciled (automatically) once they are created.

Now my problem is: I just have no idea how to fill the form view fields correctly in payment returns. Is there any documentation about it? Looks very complicated to fill all these fields. Is there any best practice about it? 

I still think that it would be a good idea just to mark an invoice as returned. And easy for the users to use.
