### ISSUE TITLE
[14.0] account_payment_return: Account used in the journal entry 

### ISSUE THREAD

**Issue by rp-landoo** [OCA/account-payment#475]
When I receive a payment order return and try to create a “Customer Payment Returns”, at the moment of validation it creates a journal entry puting the account of the customer selected to reopen the Balance and the invoice. But the problem I have is that the counterpart of the journal entry is the Bank account, which makes it impossible to reconcile with the bank move. The only solution that I have found to solve this problem, is to modify the account directly on the journal item, manually establishing the Outstanding Payments account of the Bank. Does somebody know a proper way to proceed with this?

Thanks!

**Comment by ao-landoo** [comment]
Fixed on #479
