### ISSUE TITLE
[14.0] account_payment_credit_card missing translations

### ISSUE THREAD

**Issue by bosd** [OCA/account-payment#481]
**Is your feature request related to a problem?**
All the translation files are missing in the 14.0 version of account_payment_credit_card.

In V12 there where more languages. (hr,nl,ptpt_br)
https://github.com/OCA/account-payment/tree/12.0/account_payment_credit_card/i18n

**Describe the solution you'd like**
I would like to see the language files migrated, so there is no loss of resources as mentioned in. 
https://github.com/OCA/e-commerce/issues/532

**Describe alternatives you've considered**
I have considered manually porting the translation trough weblate.
By exporting the translation files of V12 and create a new language trough weblate for v14.
Since I am only a member of the dutch language team, I cannot do this for all the translation.
A more general aproach is preferred.

**Additional context**
Am reporting this here, but this is a general issue which might occur with more modules as well.
afaik, there is no automated solution to forward port translations automatically. 
Maybe there can be an oca "migration translation" guide in the mean time.

**Comment by pedrobaeza** [comment]
Go to Weblate translation platform, export the translation of 12.0, and import it on 14.0. There's no way of automatic "fw-port" of translations if they have been done after the module migration, due to technical difficulties. The translation platform also has translation memory features, but someone has to research about how to properly use it. You can volunteer for that work if you want.

**Comment by bosd** [comment]
The export-import on weblate I can only do for the language I'm authorized for. So this would mean asking the contributors of other languages to do the same.

Would it be possible to re-do the migration procedure. Create a PR for only these translation files? Would weblate accept that?
(This procedure might even be as cumbersome as the first option)

@sbidoul I'm happy to volunteer to investigate what can be achieved with the weblate settings.

**Comment by pedrobaeza** [comment]
Yeah, that would be desirable, but the technical challenge for doing that is huge. I would go for an automatic filling of 100% match source terms across whole Weblate.

**Comment by sbidoul** [comment]
> Would it be possible to re-do the migration procedure. Create a PR for only these translation files?

That will work, as long as no one is creating the same translations on weblate at the same time, in which case we'd have a merge conflict in weblate and these are a pain to resolve cleanly.

> @sbidoul I'm happy to volunteer to investigate what can be achieved with the weblate settings.

That would be very welcome. Currently we have one weblate project per git repo and Odoo version, and then one component per addon. One thing I had in mind was investigating is if having one weblate project per git repo, across Odoo versions, would help. But that basically require setting a new weblate instance as we can't do that in production. There might be other tracks to explore, let me know what you have in mind.

**Comment by bosd** [comment]
I’m limited by having any previous knowledge about weblate or the current infrastructure.
So the information in this post could be jibberish...

> Currently we have one weblate project per git repo and Odoo version, and then one component per addon. One thing I had in mind was investigating is if having one weblate project per git repo, across Odoo versions, would help.

I agree, seems that this would helping solve some of the current issues. Maybe there are different tracks to share data between weblate instances?
From what I’ve read so far, IMO each new version of a module should be seen as a component to allow for porting of translations.

### Problem 1: There is no porting of translations between module versions
Loss of data in the newest version of the module when translation data is added while the migration is already in a PR. 
While the migration of a module is in progress new translations can be made. By the time the PR of migrated module is merged, it does not contain the latest translation data. This leads to a siginifant waste of resources, content and quality.

_Workaround_:
A translator could use the export-import functionality. But this is labour intensice and can only cover the language he is authorised to. Having someone with write permission on al languages fix this like maintainers is not advisable as it will ad to their workload. 

Possible solution:
Let the mergebot first merge the language files of the previous major version, before merging the pr in the new main branch.
(possible easier to implement than alternative below)

Alternative:
Let ocabot trigger weblate and use the automatic translation function to do a 100% string compare.
As source take the input of previous module.
(But how would this cover the issue when there is a completely new language added)
Hint: Only look at one version back, as further lookback would make it impossible to do some housekeeping on the data.
https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-autotranslate-autotranslate

https://docs.weblate.org/en/latest/user/translating.html#auto-translation

### Problem 2: If a translation data is added to version 12.0 of a module and a newer versions of the module already exsists. The data is not automatically ported to the newer version(s).

Weblate should forward port the translation. Which is a 'standard' feature of weblate, but might be limited by current infrastructure.
weblate doc:
>Internally, each project has translations to common strings propagated across other components within it by default. This lightens the burden of repetitive and multi version translation. The translation propagation can be disabled per [Component configuration](https://docs.weblate.org/en/latest/admin/projects.html)  using [Allow translation propagation](https://docs.weblate.org/en/latest/admin/projects.html#component-allow-translation-propagation) 
in case the translations should diverge.

source https://docs.weblate.org/en/latest/devel/integration.html

Thus the preferred setup in infrastructure would be that each new version of oca module would correspond to a new weblate component.

_workaround:_ Manually export the translation of V12. Import it to the newer versions. I used this method a couple of times. But it is resource intensive. One is only able to do this in weblate for the languages you’re authorized for.


### Problem 3: Very common strings needs to be translated repeatidly again from scratch.
Currently it looks like translation suggestions are’nt working cross project.
eg: between helpdesk-12.0 and stock-logistics-warehouse-12.0.

This leads to the risk of inconsistencies as everyone with little odoo experience who doesn't know what’s the “standard” translation in that language for the string can translate it slightly differently.

_Possible solution:_
Ideally there would be one main “dictionary” (right name??) for each language. This would be used for all repo’s, versions and modules.I think weblate call’s this “[Glossary](https://docs.weblate.org/en/latest/user/glossary.html#glossary)”.

However in the current infrastructure there is a separate weblate instance for each project and repo.
e.g.
- helpdesk-12.0-helpdesk_mgmt
- helpdesk-12.0-helpdesk_mgmt_fieldservice
- helpdesk-13.0-helpdesk_mgmt
- helpdesk-13.0-helpdesk_mgmt_fieldservice
So instead of one central dictionary, there are 4 in above example.

Would it be possible to Synchronise the glossary between multiple weblate instances. Or is a change in infrastructure needed?
>one weblate project per git repo

Maybe an infrastructure change can be prevented when using the [shared translation memory](https://docs.weblate.org/en/latest/admin/memory.html#translation-memory)?

### Problem 4: Due to problem 1, there is loss of information.
I noticed some older versions of modules contains more translated strings then the more recent ones.

For data consistency it is questionable if one would even want to have an automatic solution for retroactively syncing old translation data e.g. V8 to newer versions.

For some modules I chose to port the old data manually line by line, or by the import export function.
Suggestion of other translators to do the same. As it is not advisable to have this automated due to work load on servers and data consistency.

### Problem 5: There are currently no or underused inconsistency checks in place.
This does’nt look professional. For now, this is maybe not the highest priority.
When previous mentioned problems are solved, there could be a central Glossary,dictionary or translation memory to check against. Which makes it easier to implement [consistency checks](https://docs.weblate.org/en/latest/user/checks.html#check-inconsistent).

**Comment by bosd** [comment]
It sounds like an task for the oca bot, to pre-merge the lange files from the previous version branch to the merging branch.
Untill the bot is capable to do this task. 

To fix this in this particular case, and shoutout to the last contributors of their language to forward port from V12 to V14 branch.
By using the import export method.
@badbole , @pedrocasi , @marcelsavegnago would you be so kind?
