### ISSUE TITLE
account_due_list_payment_mode does not show payment mode

### ISSUE THREAD

**Issue by JGarcia-Panach** [OCA/account-payment#51]
Steps of the test (in runbot: http://3117441-8-0-4bf68a.runbot1.odoo-community.org/web?debug=1)

**1.- I create a sell payment mode.**
![1creo modo de pago para ventas](https://cloud.githubusercontent.com/assets/13234598/10843181/b26269d8-7ef7-11e5-8022-e13199385e46.JPG)

**2.- I assign the new payment mode to customer Agrolait.**
![2le asigno el modo de pago a agrolait](https://cloud.githubusercontent.com/assets/13234598/10843206/e8c2dddc-7ef7-11e5-9c1f-77f6bff0f51f.JPG)

**3.- I create a sale order with this payment mode** and validate the invoice.
![3sale order con modo de pago](https://cloud.githubusercontent.com/assets/13234598/10843227/145bd854-7ef8-11e5-8bf2-ef92218b90e2.JPG)

**4.- I check in Payments and due list** the payment mode is not shown.
![4no aparece el modo de pago en la lista de efectos](https://cloud.githubusercontent.com/assets/13234598/10843253/457aed30-7ef8-11e5-97b8-b0ab1a0d719c.JPG)

**5.- In order to show this payment** 
I have to go to invoice and select another payment mode (in this case I select blank), and save.
I select again payment mode "Direct Payment Sales" and save.
![5vuelvo a seleccionar el modo de pago](https://cloud.githubusercontent.com/assets/13234598/10843513/c0bf87b6-7ef9-11e5-928f-282988b05eb4.JPG)

**6.- And now the payment mode is shown.**
![6ahora si aparece el modo de pago](https://cloud.githubusercontent.com/assets/13234598/10843455/6fa0c2c8-7ef9-11e5-9925-ddb4886cf830.JPG)

If we find the reason, we will make the PR, but more likely someone will find it before us ...

Thanks!!

**Comment by JGarcia-Panach** [comment]
We have checked the database, and when you create an invoice it doesn't inform payment mode field:
payment_mode_id = null
![account_move_line](https://cloud.githubusercontent.com/assets/13234598/10846242/59713112-7f0e-11e5-95dd-99efb7b860db.PNG)

If you select another payment mode, the id appears
![account_move_line_actualizado](https://cloud.githubusercontent.com/assets/13234598/10846259/7626e784-7f0e-11e5-9631-4a1081ec8848.PNG)

But we don't know why

**Comment by pedrobaeza** [comment]
Please try changing the related field from `invoice.payment_mode_id` to `stored_invoice_id.payment_mode_id` and tell me if it works.

**Comment by JGarcia-Panach** [comment]
It works perfectly @pedrobaeza 
Thanks!

Should we do a PR?

**Comment by pedrobaeza** [comment]
Yes, please

**Comment by eLBati** [comment]
As the PR is merged, I close this
