### ISSUE TITLE
account_due_list_days_overdue v14 error

### ISSUE THREAD

**Issue by manuelregidor** [OCA/account-payment#576]
I have found an error with account_due_list_days_overdue module (v14).

The overdue terms created by default are as follows:

![overdue_1](https://user-images.githubusercontent.com/62256279/213115321-807bddc8-4d8b-4bd3-bd99-629746344aad.png)

I have edited the first overdue term so it covers the period between day 1 and day 14. I have also created a new overdue term that covers the period between day 15 and day 30.

![overdue_2](https://user-images.githubusercontent.com/62256279/213115631-667095cd-0f6b-436a-8fb3-0cfae449c277.png)

If you click on Invoicing > Accounting > Payment and due list, you get the following error.

![overdue_3](https://user-images.githubusercontent.com/62256279/213115903-ceb54c80-7f0c-4656-bad2-4f3787911c97.png)

Any idea why this is happening?

Thank you

**Comment by manuelregidor** [comment]
@pedrobaeza @ValentinVinagre @HaraldPanten

**Comment by pedrobaeza** [comment]
I'm not using this module.
