### ISSUE TITLE
[8.0] Unable to install account_due_list after migration 

### ISSUE THREAD

**Issue by cubells** [OCA/account-payment#59]
The database has more than 39.000 records.
The problem is that the method _maturity_residual() calls method _maturity_residual() of account_move_line model and it's very very very slow.

**Comment by pedrobaeza** [comment]
I have a database with millions of account.move.line that I needed to install this module. It took a lot, but at the end, it installs. This field is needed for performance reasons for calculating the aging of an effect. Do you have any possible improvement over the calculation?

**Comment by JordiBForgeFlow** [comment]
This is now solved, as an init hook was added https://github.com/OCA/account-payment/blob/8.0/account_due_list/init_hook.py.

Closing this issue.
