### ISSUE TITLE
[14.0] account-payment, oca_dependencies

### ISSUE THREAD

**Issue by GSLabIt** [OCA/account-payment#616]
Hi there, 

is there any reason why this:

https://github.com/OCA/account-payment/blob/7eff9835dc1953f1abbd0e3504eec5df3d31fadc/oca_dependencies.txt#L2

is needed on dependencies?

Actually referenced pr is merged: https://github.com/OCA/account-payment/pull/451

**Comment by francesco-ooops** [comment]
@OCA/banking-maintainers

**Comment by francesco-ooops** [comment]
@GSLabIt yes the error comes from here: https://github.com/OCA/account-payment/pull/453/files#r790485920

the wrong PR was referenced
