### ISSUE TITLE
[BUG] [account_payment_paired_internal_transfer] Date of account move does not respect the Date entered

### ISSUE THREAD

**Issue by douglascstd** [OCA/account-payment#626]
## Module
account_payment_paired_internal_transfer

## Describe the bug
Ony the account move from ORIGIN account move respect the date entered

![image](https://user-images.githubusercontent.com/20867090/236887224-2f33b9dd-1bda-4276-9b0e-984b368b878c.png)
![image](https://user-images.githubusercontent.com/20867090/236887257-5f7927cc-0cea-4735-b3d5-66e6fe41401c.png)
![image](https://user-images.githubusercontent.com/20867090/236887280-d41734a9-58fa-4991-8c1e-0e52244bdd31.png)

## To Reproduce
**Affected versions**: 14.0

1. Create a Payment
2. Flag "is internal transfer" field
3. Select a date diferent of the curent date
4. Post
5. Check the date of both account move, they may be wrong

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by rafaelbn** [comment]
This is solved in https://github.com/OCA/account-payment/pull/661
