### ISSUE TITLE
Transifex - Can't find project

### ISSUE THREAD

**Issue by mbcosta** [OCA/account-payment#65]
Hi
   I'm looking for the project on https://www.transifex.com/oca/public/?page=1 ,but can't find, there is any problem or the project is in another place ?

**Comment by pedrobaeza** [comment]
For being in Transifex, an OCA project should declare it via .travis.yml file. It seems nobody has done it till now. Here is the master template: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml and here the secret words: https://github.com/OCA/maintainer-quality-tools/issues/194

**Comment by mbcosta** [comment]
Thanks @pedrobaeza , I did a pull request to add the Transifex config #66

**Comment by mbcosta** [comment]
Hi @pedrobaeza , I can see the project now but there is nothing inside https://www.transifex.com/oca/OCA-account-payment-8-0/content/ , maybe I missed or did something wrong. Do you have any idea ?

**Comment by pedrobaeza** [comment]
Well, it seems a bad Travis execution. I have run it again and now all seems to be there.
