### ISSUE TITLE
[8.0] [account_payment_extension] Fail due to alter table

### ISSUE THREAD

**Issue by cubells** [OCA/account-payment#71]
Unable to upgrade module because this two columns exits:
https://github.com/OCA/account-payment/blob/8.0/account_payment_extension/migrations/8.0.1.0.0/pre-migration.py#L17-L18

Can It be checked if exist before alter table?

**Comment by pedrobaeza** [comment]
But they shouldn't exist... Remove them in your DB before migrating.

Anyway, if you want, you can program an SQL sentence to see if the column exists, and if not, call this creation sentence, but there's no unique SQL sentence to create it if not exists.

**Comment by cubells** [comment]
I saw the problem.

You are right @pedrobaeza
