### ISSUE TITLE
Module account_voucher_no_auto_lines lost in 8.0 and 9.0

### ISSUE THREAD

**Issue by ovnicraft** [OCA/account-payment#97]
I was looking for `account_voucher_no_auto_lines` module i did not find it at this branches, why was removed ?
Exists at 7.0

**Comment by pedrobaeza** [comment]
It hasn't been removed. It's just simply not migrated yet.

**Comment by ovnicraft** [comment]
So my Q was for i didnt find it here https://github.com/OCA/account-payment/tree/8.0, and is not listed in addons tables for readme, policy about this is not just mark as not installable.?

**Comment by pedrobaeza** [comment]
Because it was merged in 7.0 after the 8.0 fork. You should bring it with full commit history if you want to have it on 8.0, similar to https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
